### ISSUE TITLE
[FEATURE] Add support for PlanetSuzy.org

### ISSUE THREAD

**Issue by BosonHair** [Jules-WinnfieldX/CyberDropDownloader#846] opened 2024-03-11 23:33 UTC
Be great if you could ddd support for http://www.planetsuzy.org

**Comment by Jules-WinnfieldX** [comment] 2024-03-11 23:34
Duplicate of https://github.com/Jules-WinnfieldX/CyberDropDownloader/issues/844

**Closed by Jules-WinnfieldX** 2024-03-11 23:34 UTC
Labels: enhancement
