### ISSUE TITLE
[BUG] Program freezing / not progressing from scraping.

### ISSUE THREAD

**Issue by thomasdaley2** [Jules-WinnfieldX/CyberDropDownloader#823] opened 2024-02-19 07:55 UTC
**Describe the bug**
Program seems to hang.. no downloading and says its working but nothing ever happens.  I had it working fine but made a clean install and now its playing up.  The main repeating thing im seeing is:

INFO     : 2024-02-19 18:09:32,857 : utilities.py:95 : Download Retrying: https://simp2.saint2.su/videos/e1cd63975cbc13877e10fcba51a41e23.mp4 with attempt 8
ERROR    : 2024-02-19 18:09:32,965 : utilities.py:95 : Download Failed: https://simp2.saint2.su/videos/e1cd63975cbc13877e10fcba51a41e23.mp4 with status 1 and message ClientConnectorError(ConnectionKey(host='simp2.saint2.su', port=443, is_ssl=True, ssl=False, proxy=URL(''), proxy_auth=None, proxy_headers_hash=-3528052999497602322), gaierror(11001, 'getaddrinfo failed'))

**To Help Reproduce**

1. Run program and wait.

**Setup Information**
 - OS: Windows 11
 - Cyberdrop Downloader Version 5.1

**Downloader.log file**

https://drive.google.com/file/d/1qCUbdKwcXvVpW3t6K0YG6Jnmg4BUdPwz/view?usp=sharing

**Comment by thomasdaley2** [comment] 2024-02-19 10:03
In addition.  Opening up my backup of the old version 4 (updated to 5) It works fine.  All setting are the same. So something seems to be bugged in the fresh install... the old one didnt have that venv folder, maybe its something there?  

Anyway for now im back to hoarding with my old version.

**Comment by Jules-WinnfieldX** [comment] 2024-02-20 00:40
Duplicate of https://github.com/Jules-WinnfieldX/CyberDropDownloader/issues/791

**Closed by Jules-WinnfieldX** 2024-02-20 00:40 UTC
Labels: bug
