### ISSUE TITLE
[FEATURE] "ibb.co" support

### ISSUE THREAD

**Issue by Ace-Cook** [Jules-WinnfieldX/CyberDropDownloader#639] opened 2023-11-28 09:30 UTC
Example:

The following link presents a photo album of small-format images, each linked to the source-quality image "below" ...

https://ibb.co/album/8NNXYq?page=4&seek=bzsN9BS

Can albums from this site be added to CDD such that it scrapes the source images from all albums under the ibb.co domain?

Thanks in advance for all your amazing work!

**Comment by Jules-WinnfieldX** [comment] 2023-11-28 15:43
Duplicate of https://github.com/Jules-WinnfieldX/CyberDropDownloader/issues/592

**Closed by Jules-WinnfieldX** 2023-11-28 15:43 UTC
Labels: enhancement
