### ISSUE TITLE
[FEATURE] Add F95zone.to support

### ISSUE THREAD

**Issue by Quaso00** [Jules-WinnfieldX/CyberDropDownloader#633] opened 2023-11-24 23:40 UTC
On forums, especially in fan-art sections, dozens of pages are filled with shared images, and it becomes quite challenging to address each one individually. Therefore, can you introduce f95zone support?

**Comment by Jules-WinnfieldX** [comment] 2023-11-25 06:24
Duplicate of https://github.com/Jules-WinnfieldX/CyberDropDownloader/issues/225

This is in progress.

**Closed by Jules-WinnfieldX** 2023-11-25 06:24 UTC
Labels: enhancement
