### ISSUE TITLE
[FEATURE] Download Cyberfile folder with password

### ISSUE THREAD

**Issue by sminato27** [Jules-WinnfieldX/CyberDropDownloader#289] opened 2022-12-31 04:35 UTC
I would like to know if there's any way to download a cyberfile folder with password cuz I know the password but the app don't downloads it since isn't supported.

Please add a way to insert the password with the link or something.

![image](https://user-images.githubusercontent.com/59450675/210124938-b9e0da8f-1278-412b-9c31-6761bbdd8791.png)

**Comment by Jules-WinnfieldX** [comment] 2023-01-01 01:57
I'm considering this a duplicate of #156 

Currently there is no good way to integrate this with the current feature-set. If this changes it will be added.

**Closed by Jules-WinnfieldX** 2023-01-01 01:57 UTC
Labels: enhancement
