### ISSUE TITLE
[BUG] Bunkr Failing scrape

### ISSUE THREAD

**Issue by desligue** [Jules-WinnfieldX/CyberDropDownloader#731] opened 2023-12-17 17:26 UTC
Bunkr links are failing to scrape, tried all types of links (albuns, videos, others, direct links)
saw the other issue reports marked as resolved but mine won't work at all 
So as bunkr continues to be on the supported websites list, is there any way that it goes back to working status? 
my url.txt is almost all bunkr links, kinda stuck here

 - OS: Windows 10
 - Cyberdrop Downloader Version #5.1.3

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13697151/downloader.log)

**Comment by roxasxiv** [comment] 2023-12-17 20:34
adding "www" in front of bunkrr seems to fix it

**Comment by Jules-WinnfieldX** [comment] 2023-12-18 16:27
> saw the other issue reports marked as resolved but mine won't work at all

The other issues were closed as this isn't a Cyberdrop-DL issue, it's caused by Bunkr.

**Closed by Jules-WinnfieldX** 2023-12-18 16:27 UTC
Labels: bug
