### ISSUE TITLE
Stuck at "Failed to Download"

### ISSUE THREAD

**Issue by kopaka91** [Jules-WinnfieldX/CyberDropDownloader#24] opened 2021-07-23 18:10 UTC
Hello, I was using this downloader for a long time and it worked perfectly, then suddenly one day it stopped working. Now it always returns "Failed to Download" on every image. I've tried with different albums (which I know they all exist and work) to no avail. I downloaded the latest version but that didn't change anything.

![image](https://user-images.githubusercontent.com/87874082/126823924-1562a727-85f4-4755-b9e8-9e11c6caee18.png)
![image](https://user-images.githubusercontent.com/87874082/126823945-3187c327-740d-411f-80e0-69e8d0ae0d1f.png)

**Comment by Jules-WinnfieldX** [comment] 2021-07-23 19:36
Can you try re-downloading the utility and see if it fixes it?

I had a user experience this same issue and it seemingly resolved itself after re-downloading. If that doesn't work we can go into deeper troubleshooting.

**Comment by Jules-WinnfieldX** [comment] 2021-07-23 19:40
Out of curiousity, where did you put the CyberdropDownloader folder?

**Comment by kopaka91** [comment] 2021-07-23 19:46
I put it in a local storage Drive (D:)

D:\CyberDropDownloader-1.3.2

**Comment by Jules-WinnfieldX** [comment] 2021-07-23 19:48
While that shouldn't be a problem. Could you try just moving that folder to your regular downloads folder for example? Or your desktop? Just to test

**Comment by kopaka91** [comment] 2021-07-23 19:50
Sure. Just tested on the Desktop, and on another drive, I have the same issue.

**Comment by Jules-WinnfieldX** [comment] 2021-07-23 19:57
This is such an annoying error, I really wish windows gave more information than they do. I'm away from my main computer currently on vacation, but I'm back home later tonight. I'll create a debug branch for you to try then.

**Comment by kopaka91** [comment] 2021-07-23 20:13
Thank you, and no worries I can wait.

**Comment by Jules-WinnfieldX** [comment] 2021-07-27 02:51
https://github.com/Jules-WinnfieldX/CyberDropDownloader/archive/refs/heads/Jules-WinnfieldX-DEBUG.zip
I don't think this is going to give me much to go off, but try this anyways.

**Comment by kopaka91** [comment] 2021-07-27 03:39
This is what I got:

![image](https://user-images.githubusercontent.com/87874082/127087741-09379932-1204-48fd-8696-882a2e64af02.png)

**Comment by Jules-WinnfieldX** [comment] 2021-07-27 03:45
Can you try running these two commands in command prompt? 
pip install --upgrade requests[security]
pip install --upgrade httpie

Can you also tell me which version of Python you are using? you can find that out with the command
python --version

**Comment by kopaka91** [comment] 2021-07-27 04:08
Ok so this is what I was getting for the first 2 commands, as for the python version, seems like Windows didn't recognize that I had Python 3.9.6 (installed with their isntaller)

![image](https://user-images.githubusercontent.com/87874082/127093537-861d2055-309e-436c-ba5a-8b80179065de.png)

After seeing that I "didn't have Python" I uninstalled it, downladed it via Microsoft store, and this is what I got now:

![image](https://user-images.githubusercontent.com/87874082/127093764-cc6b182a-dcab-40c7-ae73-c25be66f544c.png)

Went ahead and tested the CyberdropDL + the DEBUG version you gave me, they both instantly close after opening (tried both the "Start.bat" and the "downloader.py".

**Comment by kopaka91** [comment] 2021-07-27 04:10
Sorry, for the DEBUG I get this, and after I press ENTER, it closes:

![image](https://user-images.githubusercontent.com/87874082/127094050-3308d3dc-e6bb-4773-8d2b-23a75a933593.png)

**Comment by Jules-WinnfieldX** [comment] 2021-07-27 04:16
Before we go down a big rabbit hole. Try running this. https://github.com/Jules-WinnfieldX/CyberDropDownloader/archive/refs/heads/Jules-WinnfieldX-DEBUG.zip

See if it makes a difference. I'd probably try restarting the computer first if you haven't done that already after installing the new version of python.

**Comment by kopaka91** [comment] 2021-07-27 04:28
Alright, restarted and tried the DEBUG:

![image](https://user-images.githubusercontent.com/87874082/127095409-93fb5097-ce17-4c08-b1c5-86e9d7f712b8.png)

And for the sake of testing, tried with a VPN, and then tried with another WiFi, this is what I get with those 2:

![image](https://user-images.githubusercontent.com/87874082/127095315-5115c0f0-12b4-4656-a13c-725b620c66a3.png)

**Comment by Jules-WinnfieldX** [comment] 2021-07-27 05:21
I don't really know what to say.. I've never seen the SSL error before (picture 1) and as far as I can tell I can only find issues with that when python is version 2.7.8 or under. 

What's even more odd is when you tried using a VPN and a different WIFI you get the proper SSL Certificate for Cyberdrop.
The connection forcibly closing itself is okay, and the downloader should be able to work through that. 

So seeing as the error changed with a different wifi into something that is workable, I'd say that the issue is with your main wifi. I'd suggest unplugging your networking equipment (router, modem, etc). For 5-10 minutes and trying again. But unfortunately I don't think this is something I'll be able to solve through changing the code or getting you to install various things. 

If it doesn't work, I can give you a work around I found that skips the SSL Verification check, but I'm not comfortable putting that into the main version of this utility for safety reasons.

**Comment by kopaka91** [comment] 2021-07-27 14:41
I see.

> So seeing as the error changed with a different wifi into something that is workable, I'd say that the issue is with your main wifi. I'd suggest unplugging your networking equipment (router, modem, etc). For 5-10 minutes and trying again. But unfortunately I don't think this is something I'll be able to solve through changing the code or getting you to install various things.

Well, that didn't fix it (not that I expected it to). I can just use a VPN or the other WiFi to go around that. 

My only gripe is that even using those the downloads take ages and fail a lot. It's taken about 10 minutes to successfully download a single image when it used to work flawlessly before, and I don't know if it's fixable (I'm guessing it isn't).

I am inclined to trying the one that skips the SSL Verification, if you don't mind giving it to me.

Other than that, thank you a ton for helping, and sorry for taking your time.

**Comment by Jules-WinnfieldX** [comment] 2021-07-27 20:02
https://github.com/Jules-WinnfieldX/CyberDropDownloader/archive/refs/heads/Insecure-SSL.zip

This should remove the SSL verification. Give it a try.

**Comment by kopaka91** [comment] 2021-07-27 20:17
It instantly closes after it opens. Both the "Start.bat" and the "Downloader.py"

**Comment by kopaka91** [comment] 2021-07-27 20:52
Closes after pressing a key

![image](https://user-images.githubusercontent.com/87874082/127225644-551783dd-bf37-462f-b352-9eb442c40a13.png)

**Comment by Jules-WinnfieldX** [comment] 2021-07-27 20:53
that ones my bad, we already went over that issue. This next one should work. Give that download a try once more.

**Comment by kopaka91** [comment] 2021-07-27 20:59
Well, it would seem like it's working now, however the images downloaded seem to be corrupted (and weirdly enough they all have a 311 bytes size). I don't think there's a way around this unfortunately, and I don't want to keep taking your time on a problem that seems to only affect me. I really appreciate the attemps though, thank you.

![image](https://user-images.githubusercontent.com/87874082/127226333-8ba7a6b5-00c7-44ad-92f2-aaa63d5e0442.png)

![image](https://user-images.githubusercontent.com/87874082/127226498-4b732efb-a0cc-4b1c-9ab2-d4d08f349e28.png)

**Comment by Jules-WinnfieldX** [comment] 2021-07-27 21:00
The one last thing I'd recommend you try is uninstall all the versions of python you have installed, and completely delete this utility and start from scratch. It's a fair amount of work, but it's the only thing I can think of at this point. Sorry I couldn't be of more help.

**Closed** 2021-07-30 18:45 UTC
