### ISSUE TITLE
[BUG] Cyberfile.is not download past first page

### ISSUE THREAD

**Issue by randomlychosenusername** [Jules-WinnfieldX/CyberDropDownloader#186] opened 2022-08-18 19:41 UTC
**Describe the bug**
A cyberfile.is folder that I am trying to download completely and spans multiple pages, does not download anything past the first page of listed files and folders.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Go to a cyberfile.is link with multiple pages of content and enter the URL into URLs.txt. Run the downloader and nothing past what was on the first page is present.
2. I do not have an example of something SFW.
3. I attempted to test this with the latest build, but it doesn't have the URLs.txt nor Start Windows.bat. I am using the most recent stable build.

**Screenshots**
![Screenshot 2022-08-18 143703](https://user-images.githubusercontent.com/111518909/185480105-c5ee64dd-5159-4826-86b5-52f0855458d8.jpg)
![Screenshot 2022-08-18 143816](https://user-images.githubusercontent.com/111518909/185480107-12fb6c70-5922-4808-a086-4539cc28b0f3.jpg)

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version # (V3 dated 3/24/22_

**Downloader.log file**
Downloader log has links to NSFW content.

**Comment by daantee0** [comment] 2022-08-19 05:08
its not problem of program the problem of website if u try to open the image i will leed u on the website it doesnt work thats whybi cant download from cyberdrop

**Comment by randomlychosenusername** [comment] 2022-08-22 13:31
@Jules-WinnfieldX This can't be by design right?

**Comment by Jules-WinnfieldX** [comment] 2022-08-22 14:15
It's not by design. I just don't have the time currently to fix. An example URL would expedite things though. JulesWinnfield#8650

**Comment by Jules-WinnfieldX** [comment] 2022-08-23 15:19
This will be fixed in the upcoming update. Trying to get through as many of these issues as I can before pushing.

**Closed by Jules-WinnfieldX** 2022-08-23 15:19 UTC
Labels: bug

**Comment by Jules-WinnfieldX** [comment] 2022-08-23 17:52
Update is out.

**Comment by randomlychosenusername** [comment] 2022-08-23 19:35
Thanks. How do you run the builds if there's no Start Windows.bat though?

**Comment by Jules-WinnfieldX** [comment] 2022-08-23 19:36
The start windows.bat is on the releases page here: https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases/

The start windows.bat file will automatically update the program when it runs (might take a try or two for it to so fully).

**Comment by randomlychosenusername** [comment] 2022-08-23 19:47
Program is updated but doesn't scrape cyberfile.is at all now. Tried running as admin as well.

![Screenshot 2022-08-23 144448](https://user-images.githubusercontent.com/111518909/186252260-6014c764-b892-4d9b-ab69-76a5d85bda76.jpg)

**Comment by Jules-WinnfieldX** [comment] 2022-08-23 19:47
Give it a few minutes.

**Comment by randomlychosenusername** [comment] 2022-08-23 20:02
Cool, I had to hit enter when I didn't before but it's getting everything it missed before. It's putting them in a new subfolder but I can live with that. Thanks again!
