### ISSUE TITLE
[FEATURE] Skip links argument

### ISSUE THREAD

**Issue by neuri48** [Jules-WinnfieldX/CyberDropDownloader#315] opened 2023-01-30 02:49 UTC
We need a way to be able to skip farm links that people post with these giant archives that were already posted/downloaded in the thread (try scraping the @m0r@nth thread lol). Just thought that it might be useful to create a function like the input file (-i) argument but for skipping links

**Comment by Jules-WinnfieldX** [comment] 2023-02-09 05:02
This would be a bit of a nightmare to implement, and it'd be somewhat of a duplicate of functionality. 

--mark-downloaded already exists. You can put all these links you want to skip into the program with that flagged (in either command or in config) and it'll mark those links as completed in the database and permanently skip them in the future.

**Closed by Jules-WinnfieldX** 2023-02-09 05:02 UTC
Labels: enhancement
